/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2021-07-16 15:45:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import logic.engclasses.bean.EventBean;
import logic.engclasses.bean.ArtistBean;
import logic.engclasses.utils.SessionUser;
import java.util.List;
import logic.appcontroller.HomepageUserController;

public final class HomepageUsers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("logic.engclasses.utils.SessionUser");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("logic.appcontroller.HomepageUserController");
    _jspx_imports_classes.add("logic.engclasses.bean.ArtistBean");
    _jspx_imports_classes.add("logic.engclasses.bean.EventBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n      \r\n    \r\n    \r\n    \r\n    \r\n        \r\n    ");
	HomepageUserController huc = new HomepageUserController(); 
      out.write('\r');
      out.write('\n');
		List<EventBean> events = huc.liveEventsList();
	SessionUser su = SessionUser.getInstance();
    String username = su.getUsername();
    String artist1 = "";
    String artist2 = "";
    String artist3= "";
    String control="";
   
    int size = events.size();

      out.write("\r\n<!DOCTYPE html>\r\n<html  lang=\"it\">\r\n\r\n  <head>\r\n   <script src=\"https://www.paypal.com/sdk/js?currency=EUR&client-id=ASMN00dOM4cH1cFqKX7v1J9auNbG9yaEt2g31rZ4ID8RE8RWmNxdFrT3UEaXWUgS1x510P4QH2SJj7eX\"> </script>\r\n      <div style=\"background-color: green; display: none\" id=\"transition\">Grazie per il tuo pagamento!</div>\r\n\r\n    <title>Prova</title>\r\n  </head>\r\n  <body style=\" height: 512px; background-color: white;\"><img src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/26362.png?raw=true\"\r\n\r\n      alt=\"\" style=\"width: 93px; height: 73px; margin-left: -2px;\"><br>\r\n   \r\n    <h1 style=\"margin-top: -45.5667px; margin-left: 115px;\">ShowRoome</h1>  \r\n                                    \r\n    <h1 style=\"margin-top:84px;margin-left:3px;\">\r\n     \r\n      <form action=\"TastoChart\" method=\"post\">\r\n        <p  style=\"margin-top:-74px;margin-left:170px;\"><input id=\"Submit\" name=\"Chart\" type=\"submit\" value=\"Chart\" \" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 570px;background-color: #4D4D4D;\"></input>\r\n");
      out.write("        </p>\r\n      </form>\r\n      <form action=\"TastoMap\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:-170px;\"><input id=\"Submit\" name=\"Map\" type=\"submit\" value=\"Map\"  style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 570px;background-color: #4D4D4D;\"></input>\r\n        </p>\r\n      </form>\r\n      <form action=\"Homepage\" method=\"post\">\r\n        <p style=\"margin-top:-74px;margin-left:-555px;\"><input id=\"Submit\" type=\"submit\" name=\"Homepage\" value=\"Homepage\" style=\"height: 35px ; width: 95px; margin-top: -46px; margin-left: 570px;color:white; background-color: #4D4D4D;\"></input>\r\n        </p>\r\n      </form>\r\n      <form action=\"HostShowWebController\" method=\"get\">\r\n        <p style=\"margin-top:-74px;margin-left:937px;\"><input id=\"Submit\" type=\"submit\" name=\"Setting\" value=\"Sponsored\" style=\"height: 35px ; width: 95px; margin-top: -48px; margin-left: 210px;background-color: #4D4D4D;\"></input></p>\r\n      </form>\r\n    </h1>\r\n    <h1 style=\"margin-top: -74px;margin-left:px ;background-color: white;\">\r\n");
      out.write("      <style>\r\n  \r\n#rectangle {\r\n    width: 1250px;\r\n    height: 50px;\r\n    background: #10030F;\r\n}\r\n</style> <div id=\"rectangle\"></div>\r\n    </h1>\r\n          <h1 style=\"margin-top: -159px; margin-left: 1100px;\"> <input value=");
      out.print(username );
      out.write(" size=\"65\" maxlength=\"40\" ;style=\"background-color:\" #10030f=\"\" type=\"submit\"> </h1>\r\n         <form action=\"Logout\" method=\"post\">          <h1 style=\"margin-left: 1190px;margin-top: -57px;\" > <input value=\"logout\" size=\"65\" maxlength=\"40\" ;style=\"background-color:\" #10030f=\"\" type=\"submit\"> </h1></form> \r\n\r\n  ");
     try{
	artist1 = events.get(0).getArtist();
     } catch (Exception e){
    	 artist1 = "no artist found";
     }
    
      out.write(" \r\n    ");
if(artist1.equals("no artist found")){ 
      out.write("\r\n    \r\n    ");
 }
      out.write("\r\n        ");
if(!artist1.equals("no artist found")){ 
      out.write("\r\n    <!-- Primo artista  -->\r\n");
     try{
	artist1 = events.get(0).getArtist();
     } catch (Exception e){
    	 artist1 = "no review found";
     }
    
      out.write(" \r\n    <p style=\"margin-top: 300px; margin-left: 5px;\"> <img alt=\"\" src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/1019.jpg?raw=true\"\r\n\r\n        style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    \r\n    </p>\r\n \r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label>    ");
      out.print(events.get(0).getArtist() );
      out.write("\r\n    </label></h2>\r\n    <h3 style=\" margin-top: px;margin-left: 300px;\"> <textarea id=\"story\" name=\"story\" style=\" resize: none ;\"rows=\"5\" cols=\"80\" readonly disabled=\"disabled\">\r\n");
      out.print(events.get(0).getDescription() );
      out.write("\r\n</textarea></h3>\r\n\r\n      <input type=\"text\" id=\"payInput0\"  style=\"height: 35px; width: 90px; margin-top: -90px; margin-left: 1030px; \"  /><button id=\"Dona0\" onClick=\"generatePayment0(document.getElementById('payInput0').value)\">Dona</button>\r\n      <button  style=\"display:none;margin-top: -20x; margin-left: 1128px;\" id=\"cancella\" onClick=\"cancella()\">Cancella</button> \r\n <label style=\" margin-top: px;margin-left: 300px;\">-");
      out.print(huc.getPlace(events.get(0).getPlace()).getAddress()  );
      out.write("</label>\r\n     <label  style=\" margin-top: px;margin-left: 50px;\">");
      out.print(huc.getArtist(events.get(0).getArtist()).getTalent() );
      out.write("</label>\r\n         <label  style=\" margin-top: px;margin-left: 50px;\"></label>\r\n\r\n    <hr style=\"align:left;size:1 ;width:1200px ;color:black; noshade;\"></hr>\r\n");
 }
      out.write("\r\n\r\n\r\n");
     try{
	artist2 = events.get(1).getArtist();
     } catch (Exception e){
    	 artist2 = "no artist found";
     }
    
      out.write(" \r\n    ");
if(artist2.equals("no artist found")){ 
      out.write("\r\n    \r\n    ");
 }
      out.write("\r\n        ");
if(!artist2.equals("no artist found")){ 
      out.write("\r\n\r\n<!-- secondo artista --> \r\n\r\n   <p style=\"margin-top: 280px; margin-left: 5px;\"> <img alt=\"\" src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/chitarra%20duomo%20artisti%20strada-2.jpg?raw=true\"\r\n\r\n        style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    \r\n    </p>\r\n \r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label>    ");
      out.print(events.get(1).getArtist() );
      out.write("\r\n    </label></h2>\r\n    <h3 style=\" margin-top: px;margin-left: 300px;\"> <textarea id=\"story\" name=\"story\" style=\" resize: none ;\"rows=\"5\" cols=\"80\" readonly disabled=\"disabled\">\r\n");
      out.print(events.get(1).getDescription() );
      out.write("\r\n</textarea></h3>\r\n      <input type=\"text\" id=\"payInput1\"  style=\"height: 35px; width: 90px; margin-top: -90px; margin-left: 1030px; \"  /><button id=\"Dona1\" onClick=\"generatePayment1(document.getElementById('payInput1').value)\">Dona</button>\r\n        <button  style=\"display:none;margin-top: -20x; margin-left: 1128px;\" id=\"cancella1\" onClick=\"cancella()\">Cancella</button> \r\n  \r\n <label  style=\" margin-top: px;margin-left: 300px;\">-");
      out.print(huc.getPlace(events.get(1).getPlace()).getAddress()  );
      out.write("</label>\r\n     <label  style=\" margin-top: px;margin-left: 50px;\">");
      out.print(huc.getArtist(events.get(1).getArtist()).getTalent() );
      out.write("</label>\r\n         <label  style=\" margin-top: px;margin-left: 50px;\"></label>\r\n\r\n    <hr style=\"align:left;size:1 ;width:1200px ;color:black; noshade;\"></hr>\r\n    ");
 }
      out.write("\r\n \r\n  <!-- terzo artista  -->\r\n  \r\n  ");
     try{
	artist3 = events.get(2).getArtist();
     } catch (Exception e){
    	 artist3 = "no artist found";
     }
    
      out.write(" \r\n    ");
if(artist3.equals("no artist found")){ 
      out.write("\r\n    \r\n    ");
 }
      out.write("\r\n        ");
if(!artist3.equals("no artist found")){ 
      out.write("\r\n    \r\n   <p style=\"margin-top: 250px; margin-left: 5px;\"> <img alt=\"\" src=\"https://github.com/Brauzi35/ShowRoome-ISPW2021/blob/main/Immagini/124232574-1befbb5d-1e7d-4a4d-bb09-411ee9b05c27.jpg?raw=true\"\r\n\r\n        style=\"width: 235px; height: 155px; margin-left: -4px; margin-top: -357px;\">\r\n    \r\n    </p>\r\n    <h2 style=\" margin-top: -180px;margin-left: 300px;\"> <label >    ");
      out.print(events.get(2).getArtist() );
      out.write("\r\n    </label></h2>\r\n    <h3 style=\" margin-top: px;margin-left: 300px;\"> <textarea id=\"story\" name=\"story\" style=\" resize: none ;\"rows=\"5\" cols=\"80\" readonly disabled=\"disabled\">\r\n");
      out.print(events.get(2).getDescription() );
      out.write("\r\n</textarea></h3>\r\n       <input type=\"text\" id=\"payInput2\"  style=\"height: 35px; width: 90px; margin-top: -90px; margin-left: 1030px; \"  /><button id=\"Dona2\" onClick=\"generatePayment2(document.getElementById('payInput2').value)\">Dona</button> \r\n        <button  style=\"display:none;margin-top: -20x; margin-left: 1128px;\" id=\"cancella\" onClick=\"cancella()\">Cancella</button> \r\n  \r\n <label  style=\" margin-top: px;margin-left: 300px;\">-");
      out.print(huc.getPlace(events.get(2).getPlace()).getAddress()  );
      out.write("</label>\r\n     <label  style=\" margin-top: px;margin-left: 50px;\">");
      out.print(huc.getArtist(events.get(2).getArtist()).getTalent() );
      out.write("</label>\r\n         <label  style=\" margin-top: px;margin-left: 50px;\"></label>\r\n\r\n    <hr style=\"align:left;size:1 ;width:1200px ;color:black; noshade;\"></hr>\r\n \r\n   <form action=\"&lt;%= request.getContextPath() %&gt;/register\" method=\"post\">\r\n        <p style=\"margin-top:65px;margin-left:410px;\"><button  disabled=\"true\" name=\"Chart\" style=\"height: 35px; width: 95px; margin-top: -48px; margin-left: 160px;background-color: #4D4D4D;\">Vedi altri</button></p>\r\n      </form>\r\n      ");
} 
      out.write("\r\n    <h3 style=\"margin-top: -1225px; margin-left: 1000px;\"></h3>\r\n\r\n  \r\n     <div id=\"paypal-button-container0\"  style=\"margin-top: 300px; margin-left: 1000px; width: 115px;height: 85px; fundingicons: 'true';\"> </div>\r\n      <div id=\"paypal-button-container1\"  style=\"margin-top:300px; margin-left: 1000px; width: 115px;height: 85px; fundingicons: 'true';\"> </div>\r\n      <div id=\"paypal-button-container2\"  style=\"margin-top:260px; margin-left: 1000px; width: 115px;height: 85px; fundingicons: 'true';\"> </div>\r\n \r\n  <script> \r\n   \r\n   function  cancella(){\r\n\t\t\r\n\t     document.getElementById(\"paypal-button-container0\").style.display=\"none\";\r\n\t\t document.getElementById(\"paypal-button-container1\").style.display=\"none\";\r\n\t\t document.getElementById(\"paypal-button-container2\").style.display=\"none\";\r\n\t\t document.getElementById(\"Dona0\").disabled = false;\r\n\t\t document.getElementById(\"payInput0\").disabled = false;\r\n\t\t document.getElementById(\"Dona1\").disabled = false;\r\n\t\t document.getElementById(\"payInput1\").disabled = false;\r\n");
      out.write("\t\t document.getElementById(\"Dona2\").disabled = false;\r\n\t\t document.getElementById(\"payInput2\").disabled = false;\r\n\t\t document.getElementById(\"cancella\").style.display=\"none\";\r\n\t\t \r\n\t\t\r\n\t\t history.go(0);\r\n\r\n   }\r\n\t\t </script>\r\n   \r\n   \r\n   \r\n   \r\n   \r\n   \r\n   \r\n   \r\n   \r\n   \r\n   \r\n   \r\n   <script>\r\n  function  generatePayment0(value){\r\n\t\t document.getElementById(\"paypal-button-container0\").style.display=\"block\";\r\n\r\n    if(value==\"\"){\r\n\talert(\"inserire un importo\");\r\n\treturn;\r\n\t}\r\n\tpaypal.Buttons({\r\n\t\t style: {\r\n\t\t\t  layout: 'horizontal',\r\n\t\t\t  fundingicons: 'true',\r\n\t\t  },\r\n\tcreateOrder: function(data, actions){\r\n\treturn actions.order.create({\r\n\tpurchase_units: [{\r\n\t  amount: {\r\n\t  value : value\r\n\t  }\r\n\t  }]\r\n\t  });\r\n\t  },\r\n\t  onApprove : function(data, actions){\r\n\t  return actions.order.capture().then(function(details){\r\n\t    document.getElementById(\"transition\").style.display = \"block\";\r\n\t  });\r\n\t  }\r\n\t \r\n\t  }).render('#paypal-button-container0');\r\n\t document.getElementById(\"Dona0\").disabled = true;\r\n\t document.getElementById(\"payInput0\").disabled = true;\r\n");
      out.write("\t document.getElementById(\"cancella\").style.display=\"block\";\r\n\t   \r\n\r\n\t  }\r\n\t  </script>\r\n \r\n   <script>\r\n  function  generatePayment1(value){\r\n    if(value==\"\"){\r\n\talert(\"inserire un importo\");\r\n\treturn;\r\n\t}\r\n\tpaypal.Buttons({\r\n\t\t style: {\r\n\t\t\t  layout: 'horizontal',\r\n\t\t\t  fundingicons: 'true',\r\n\t\t  },\r\n\tcreateOrder: function(data, actions){\r\n\treturn actions.order.create({\r\n\tpurchase_units: [{\r\n\t  amount: {\r\n\t  value : value\r\n\t  }\r\n\t  }]\r\n\t  });\r\n\t  },\r\n\t  onApprove : function(data, actions){\r\n\t  return actions.order.capture().then(function(details){\r\n\t    document.getElementById(\"transition\").style.display = \"block\";\r\n\t  });\r\n\t  }\r\n\t \r\n\t  }).render('#paypal-button-container1');\r\n\t document.getElementById(\"Dona1\").disabled = true;\r\n\t document.getElementById(\"payInput1\").disabled = true;\r\n\t document.getElementById(\"cancella1\").style.display=\"block\";\r\n\r\n\t  }\r\n\t  </script>\r\n  \r\n  \r\n  <script>\r\n  function  generatePayment2(value){\r\n    if(value==\"\"){\r\n\talert(\"inserire un importo\");\r\n\treturn;\r\n\t}\r\n\tpaypal.Buttons({\r\n");
      out.write("\t\t style: {\r\n\t\t\t  layout: 'horizontal',\r\n\t\t\t  fundingicons: 'true',\r\n\t\t  },\r\n\tcreateOrder: function(data, actions){\r\n\treturn actions.order.create({\r\n\tpurchase_units: [{\r\n\t  amount: {\r\n\t  value : value\r\n\t  }\r\n\t  }]\r\n\t  });\r\n\t  },\r\n\t  onApprove : function(data, actions){\r\n\t  return actions.order.capture().then(function(details){\r\n\t    document.getElementById(\"transition\").style.display = \"block\";\r\n\t  });\r\n\t  }\r\n\t \r\n\t  }).render('#paypal-button-container2');\r\n\t document.getElementById(\"Dona2\").disabled = true;\r\n\t document.getElementById(\"payInput2\").disabled = true;\r\n\t document.getElementById(\"cancella2\").style.display=\"block\";\r\n\r\n\t  }\r\n\t  </script>\r\n  \r\n  </body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
